[project]
name = "mada-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "redis>=5.2.1",
    "setuptools>=78.1.0",
]
